# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Paumarí spellchecker"
pad = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Paumarí, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
pad = "TRANSLATE: A spellchecker for Paumarí, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.pad"

[windows]
system_product_code = "{REPLACE_WITH_REAL_SYSTEM_PROD_CODE}_is1"

[package.speller]
name = "Paumarí"
version = "0.1.0"

[package.grammar]
name = "Paumarí"
version = "0.1.0"

[package.tts-textproc]
name = "Paumarí"
version = "0.1.0"

[package.hyphenator]
name = "Paumarí"
version = "0.1.0"
