template = "https://github.com/giellalt/template-lang-und"
rev_id = 264
template_sha = "120f384c016282eb1fbbcc762e0ac6064a37eb45"

[replacements]
__GLOTTOLOG_ID__ = "paum1247"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-pad"
__UND2C__ = "pad"
__UNDEFINED__ = "Paumar√≠"
__UND__ = "pad"
