template = "https://github.com/giellalt/template-lang-und"
rev_id = 225
template_sha = "f41519ddc2fe90fa957f23f2acb5b371f70bf4e4"

[replacements]
__LICENSE__ = "GPLv3"
__REPO__ = "lang-pad"
__UND2C__ = "pad"
__UNDEFINED__ = "Paumar√≠"
__UND__ = "pad"
